name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: linux_injection_detector
        parth: injection_detector
    - name: releaser-action-linux
      uses: unfor19/release-action@1.0.0
      
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: windows_injection_detector
        parth: injection_detector.exe
    - name: releaser-action-windows
      uses: unfor19/release-action@1.0.0

