name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: mxkcw/upload_github_release_assets_action@v0.0.5
      with:
        name: linux_injection_detector
        filename: injection_detector*
        path: .
        tag: 0.2
        tag_name: '{github.GITHUB_REF}'

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: mxkcw/upload_github_release_assets_action@v0.0.5
      with:
        name: windows_injection_detector
        filename: injection_detector*
        path: .
        tag: 0.2
        tag_name: '{github.GITHUB_REF}'
