name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Release build linux_injection_detector
      uses: george012/upload_github_release_assets_action@latest
      with:
        path: ./injection_detector*

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Release build windows_injection_detector
      uses: george012/upload_github_release_assets_action@latest
      with:
        path: ./injection_detector*
